###
POST http://localhost:5002/get-inventory-by-id
content-type: application/json

{
  "id": "90c9479e-a11c-4d6d-aaaa-0405b6c0efcd"
}

###
POST http://localhost:5002/get-inventories-by-ids
content-type: application/json

{
 "ids": "90c9479e-a11c-4d6d-aaaa-0405b6c0efcd,b8b62196-6369-409d-b709-11c112dd023f,ec186ddf-f430-44ec-84e5-205c93d84f14"
}
