// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VND.FW.Infrastructure.EfCore.Db;

namespace VND.CoolStore.Services.Cart.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20180720083523_initDb")]
    partial class initDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VND.CoolStore.Services.Cart.Domain.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("CartItemPromoSavings");

                    b.Property<double>("CartItemTotal");

                    b.Property<double>("CartTotal");

                    b.Property<DateTime>("Created");

                    b.Property<double>("ShippingPromoSavings");

                    b.Property<double>("ShippingTotal");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("VND.CoolStore.Services.Cart.Domain.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CartId");

                    b.Property<DateTime>("Created");

                    b.Property<Guid>("ProductIdId");

                    b.Property<double>("PromoSavings");

                    b.Property<int>("Quantity");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductIdId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("VND.CoolStore.Services.Cart.Domain.ProductId", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("ProductIds");
                });

            modelBuilder.Entity("VND.CoolStore.Services.Cart.Domain.CartItem", b =>
                {
                    b.HasOne("VND.CoolStore.Services.Cart.Domain.Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId");

                    b.HasOne("VND.CoolStore.Services.Cart.Domain.ProductId", "ProductId")
                        .WithMany()
                        .HasForeignKey("ProductIdId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
