// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VND.CoolStore.Services.Cart.Infrastructure.Db;

namespace VND.CoolStore.Services.Cart.Migrations
{
    [DbContext(typeof(CartDbContext))]
    partial class CartDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("VND.CoolStore.Services.Cart.Domain.Cart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("CartItemPromoSavings");

                    b.Property<double>("CartItemTotal");

                    b.Property<double>("CartTotal");

                    b.Property<DateTime>("Created");

                    b.Property<bool>("IsCheckout");

                    b.Property<double>("ShippingPromoSavings");

                    b.Property<double>("ShippingTotal");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("VND.CoolStore.Services.Cart.Domain.CartItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("CartId");

                    b.Property<DateTime>("Created");

                    b.Property<double>("Price");

                    b.Property<Guid>("ProductId");

                    b.Property<double>("PromoSavings");

                    b.Property<int>("Quantity");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("VND.CoolStore.Services.Cart.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ProductId");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("VND.CoolStore.Services.Cart.Domain.CartItem", b =>
                {
                    b.HasOne("VND.CoolStore.Services.Cart.Domain.Cart")
                        .WithMany("CartItems")
                        .HasForeignKey("CartId");

                    b.HasOne("VND.CoolStore.Services.Cart.Domain.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
