# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://thornelabs.net/2014/11/13/multi-machine-vagrantfile-with-shorter-cleaner-syntax-using-json-and-loops.html
boxes = [
  {
    :name => "master01",
    :mem => "2048",
    :cpu => "2"
  },
  {
    :name => "worker01",
    :mem => "1024",
    :cpu => "1"
  },
  {
    :name => "worker02",
    :mem => "1024",
    :cpu => "1"
  }
]

Vagrant.configure(2) do |config|

  config.vm.box = "generic/ubuntu1810"

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false

  # Turn off shared folders
  config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

  boxes.each do |opts|
    config.vm.define opts[:name] do |subconfig|
      subconfig.vm.provider :hyperv do |hyperv|
        hyperv.vmname = opts[:name]
        hyperv.memory = opts[:mem]
        hyperv.cpus = opts[:cpu]
      end

      subconfig.vm.hostname = opts[:name]
      subconfig.vm.network "private_network", type: "dhcp", bridge: "sample_switch"
    end
  end
end