# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "generic/ubuntu1810"

  # Disable the new default behavior introduced in Vagrant 1.7, to
  # ensure that all Vagrant machines will use the same SSH key pair.
  # See https://github.com/mitchellh/vagrant/issues/5005
  config.ssh.insert_key = false

  config.vm.provider :hyperv do |hyperv|
    hyperv.vmname = "ubuntu-master1"
    hyperv.memory = 2048
  end

  config.vm.hostname = "master1"
  config.vm.network "private_network", type: "dhcp", bridge: "sample_switch"

end