##########################################
## Node: Product Catalog Service
##########################################

@productId = "{{$guid}}"

###
GET http://localhost:5002/api/products HTTP/1.1 
content-type: application/json
### 
GET http://localhost:5002/api/products/{{productId}} HTTP/1.1
###
POST http://localhost:5002/api/products HTTP/1.1
content-type: application/json

{
    "id": "{{$guid}}",
    "name": "product {{$guid}}",
    "desc": "desc for product {{$guid}}",
    "price": 20.05
}