###
# @name auth
POST http://localhost:5001/connect/token HTTP/1.1
content-type: application/x-www-form-urlencoded

grant_type=password
&client_id=coolstore.password
&client_secret=49C1A7E1-0C79-4A89-A3D6-A37998FB86B0
&username=bob
&password=bob

###
GET http://localhost:5003/api/products/1/5000 HTTP/1.1
content-type: {{contentType}}
authorization: bearer {{auth.response.body.access_token}}

###
GET http://localhost:5003/api/products/fee1fc67-7469-4490-b418-47f4732de53f HTTP/1.1
content-type: {{contentType}}
authorization: bearer {{auth.response.body.access_token}}
