@token = xxxxxxxxxxxxxxx

##########################################
## Product Catalog Service
##########################################

@productId = "{{$guid}}"

###
GET http://localhost:5000/api/v2/products HTTP/1.1 
content-type: application/json
authorization: Bearer {{token}}
### 
GET http://localhost:5000/api/v2/products/{{productId}} HTTP/1.1
###
POST http://localhost:5000/api/v2/products HTTP/1.1
content-type: application/json

{
    "id": "{{$guid}}",
    "name": "product {{$guid}}",
    "desc": "desc for product {{$guid}}",
    "price": 1000
}

##########################################
## Inventory Service
##########################################

### 
GET http://localhost:5000/api/v2/availability/{{itemId}} HTTP/1.1

##########################################
## Pricing Service
##########################################


##########################################
## Rating Service
##########################################

### 
GET http://localhost:5000/api/v2/ratings/{{itemId}} HTTP/1.1

###
POST http://localhost:5000/api/v2/ratings HTTP/1.1
content-type: application/json

{
    "itemId": "{{itemId}}",
    "rating": 5
}

##########################################
## Review Service
##########################################

###
GET http://localhost:5000/api/v2/reviews/{{itemId}} HTTP/1.1

##########################################
## Cart Service
##########################################

@cartId = "{{$guid}}"
@itemId = "{{$guid}}"
@quantity = 1

### 
GET http://localhost:5000/api/v2/carts/{{cartId}} HTTP/1.1
###
POST http://localhost:5000/api/v2/carts HTTP/1.1
content-type: application/json

{
    "cartId": "{{cartId}}",
    "itemId": "{{itemId}}",
    "quantity": "{{quantity}}"
}
###
PUT http://localhost:5000/api/v2/carts/{{cartId}}/item/{{itemId}} HTTP/1.1
content-type: application/json

{}
###
DELETE http://localhost:5000/api/v2/carts/{{cartId}}/item/{{itemId}} HTTP/1.1
content-type: application/json

{
   "quantity": "{{quantity}}" 
}
###
POST http://localhost:5000/api/v2/carts/{{cartId}}/checkout HTTP/1.1
content-type: application/json

{
}

