- hosts: master01
  become: yes
  gather_facts: false
  tasks:
    - name: disable swap
      shell: |
        swapoff -a

    - name: " start and enable Docker service"
      service:
        name: docker
        state: started
        enabled: yes

    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  become: yes
  tasks:
    - name: join cluster
      shell: "{{ hostvars['master01'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt