##########################################
## Node: Rating Service
##########################################

@ratingId = "{{$guid}}"

###
GET http://localhost:5002/api/ratings HTTP/1.1 
content-type: application/json
### 
GET http://localhost:5002/api/ratings/{{ratingId}} HTTP/1.1
###
POST http://localhost:5002/api/ratings HTTP/1.1
content-type: application/json

{
    "id": "{{$guid}}",
    "name": "rating {{$guid}}",
    "desc": "desc for rating {{$guid}}",
    "price": 20.05
}