##########################################
## Node: Rating Service
##########################################

@ratingId = "954536a0-a5cd-11e8-919f-5ba353fbac59"

###
GET http://localhost:5007/api/ratings HTTP/1.1 
content-type: application/json
### 
GET http://localhost:5007/api/ratings/{{ratingId}} HTTP/1.1
###
POST http://localhost:5007/api/ratings HTTP/1.1
content-type: application/json

{"ProductId":"954536a0-a5cd-11e8-919f-5ba353fbac59","UserId":"51db5230-ef16-4e5f-ad5f-1820c2cc7a99","Cost":5}